export const BANDEIRAS: Record<string, string> = {
  'Brazil':       'br',
  'Argentina':    'ar',
  'France':       'fr',
  'Germany':      'de',
  'England':      'gb-eng',
  'Spain':        'es',
  'Portugal':     'pt',
  'Netherlands':  'nl',
  'Belgium':      'be',
  'Uruguay':      'uy',
  'Colombia':     'co',
  'Mexico':       'mx',
  'USA':          'us',
  'Canada':       'ca',
  'Japan':        'jp',
  'South Korea':  'kr',
  'Morocco':      'ma',
  'Senegal':      'sn',
  'Australia':    'au',
  'Switzerland':  'ch',
  'Croatia':      'hr',
  'Denmark':      'dk',
  'Sweden':       'se',
  'Norway':       'no',
  'Austria':      'at',
  'Turkey':       'tr',
  'Iran':         'ir',
  'Saudi Arabia': 'sa',
  'Qatar':        'qa',
  'Ecuador':      'ec',
  'Paraguay':     'py',
  'Chile':        'cl',
  'Peru':         'pe',
  'Serbia':       'rs',
  'Poland':       'pl',
  'Czech Republic': 'cz',
  'Slovakia':     'sk',
  'Hungary':      'hu',
  'Scotland':     'gb-sct',
  'Wales':        'gb-wls',
  'Ireland':      'ie',
  'Ghana':        'gh',
  'Nigeria':      'ng',
  'Ivory Coast':  'ci',
  'Cameroon':     'cm',
  'DR Congo':     'cd',
  'South Africa': 'za',
  'Egypt':        'eg',
  'Tunisia':      'tn',
  'Algeria':      'dz',
  'New Zealand':  'nz',
  'Panama':       'pa',
  'Haiti':        'ht',
  'Jamaica':      'jm',
  'Costa Rica':   'cr',
  'Honduras':     'hn',
  'Cape Verde':   'cv',
  'Jordan':       'jo',
  'Iraq':         'iq',
  'Uzbekistan':   'uz',
  'Bosnia & Herzegovina': 'ba',
  'Curaçao':      'cw',
}

export function getBandeira(nomeTime: string): string | null {
  return BANDEIRAS[nomeTime] ?? null
}